### PR TITLE
Add image input node 

### PR DESCRIPTION
**Pull request by matan1905**
As per pixelworldai fork

### CODE REVIEW

**Comment by matan1905** [comment]
@pixelworldai are you ok with me taking this code to the main fork?

**Comment by pixelworldai** [comment]
@matan1905 Sure! It'd be cool to have this in ComfyUI manager :)
This is my first fork so I'm not sure how this usually works, but would I show up as a contributor on the main fork?

**Comment by matan1905** [comment]
@pixelworldai  yes you will be shown like in here:
image

**Comment by pixelworldai** [comment]
Works for me!

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
